# See tests/README.rst for instructions for using travis with developer builds.

language: python

sudo: false

python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '2.6'

# OSX builds do not yet support Python
os: linux

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - libssl1.0.0
      - djvulibre-bin
      - liblua5.1-0-dev

before_install:
  # python-coverage package creates `python-coverage` instead of `coverage`.
  # ~/bin/ is in PATH, but hasnt been created.
  - |
    if [[ -f /usr/bin/python-coverage ]]; then
      mkdir -p ~/bin/
      ln -s /usr/bin/python-coverage ~/bin/coverage
    fi

  # When PYSETUP_TEST_EXTRAS is not enabled, do not allow the
  # default 'install' step to install all dependencies listed in
  # requirements.txt to verify that a minimal install works as expected.
  # Instead install requests in the before_script step below.
  - |
    if [[ "$PYSETUP_TEST_EXTRAS" != '1' ]]; then
      rm requirements.txt
    else
      if python -c "import PIL.ImageTk" 2>/dev/null ; then
        echo "Found PIL; removing Pillow"
        sed -i '/^Pillow/d' requirements.txt
      fi
    fi

  # When the env variable USE_NOSE or USE_PYTEST is set, the appropriate
  # tool is used, else PYTEST is taken as the default
  - if [[ "$PYSETUP_TEST_EXTRAS" != '1' && "$USE_NOSE" != '1' && "$USE_PYTEST" != '1' ]]; then
      export USE_PYTEST=1 ;
    fi

  - if [[ "$SITE_ONLY" == '1' ]]; then
      echo "Running site tests only code ${LANGUAGE} on family ${FAMILY}" ;
    fi

  - export GITHUB_USER=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 1`
  - mkdir ~/.python-eggs
  - chmod 700 ~/.python-eggs

  - if [[ "$GITHUB_USER" != "wikimedia" ]]; then
      export PYWIKIBOT2_TEST_WRITE_FAIL=1 ;
    fi

before_script:
  - pip install -r dev-requirements.txt

script:
  # Install security packages for requests to support HTTPS in site_detect
  # this shouldnt be necessary, but site installed requests doesnt have 'security'
  - pip install mwoauth -r requests-requirements.txt ;

  - mkdir ~/.pywikibot

  - python pwb.py generate_family_file 'https://wiki.musicbrainz.org/' musicbrainz 'n'
  - if [[ $FAMILY == 'wpbeta' ]]; then
      python -m generate_family_file 'http://'$LANGUAGE'.wikipedia.beta.wmflabs.org/' 'wpbeta' 'n' ;
    fi
  - if [[ $FAMILY == 'wsbeta' ]]; then
      python -m generate_family_file 'http://'$LANGUAGE'.wikisource.beta.wmflabs.org/' 'wsbeta' 'n' ;
    fi

  - python -W error::UserWarning -m generate_user_files -dir:~/.pywikibot/ -family:$FAMILY -lang:$LANGUAGE -v -user:"$PYWIKIBOT2_USERNAME"

  - if [[ -n "$USER_PASSWORD" && -n "$PYWIKIBOT2_USERNAME" ]]; then
      printf "usernames['wikipedia']['en'] = '%q'\n" "$PYWIKIBOT2_USERNAME" >> ~/.pywikibot/user-config.py ;
      printf "usernames['wikipedia']['test'] = '%q'\n" "$PYWIKIBOT2_USERNAME" >> ~/.pywikibot/user-config.py ;
      printf "usernames['wikidata']['test'] = '%q'\n" "$PYWIKIBOT2_USERNAME" >> ~/.pywikibot/user-config.py ;
      printf "usernames['commons']['commons'] = '%q'\n" "$PYWIKIBOT2_USERNAME" >> ~/.pywikibot/user-config.py ;
      printf "('%q', '%q')\n" "$PYWIKIBOT2_USERNAME" "$USER_PASSWORD" > ~/.pywikibot/passwordfile ;
      echo "import os" >> ~/.pywikibot/user-config.py ;
      echo "password_file = os.path.expanduser('~/.pywikibot/passwordfile')" >> ~/.pywikibot/user-config.py ;
    fi

  - if [[ -n "$OAUTH_DOMAIN" ]]; then
      if [[ -n "$OAUTH_PYWIKIBOT2_USERNAME" ]]; then
        printf "usernames['${FAMILY}']['${LANGUAGE}'] = '%q'\n" "$OAUTH_PYWIKIBOT2_USERNAME" >> ~/.pywikibot/user-config.py ;
      fi ;
      oauth_token_var="OAUTH_TOKENS_${FAMILY^^}_${LANGUAGE^^}" ;
      if [[ -n "${!oauth_token_var}" ]]; then
        printf "authenticate['${OAUTH_DOMAIN}'] = ('%s')\n" "${!oauth_token_var//:/', '}" >> ~/.pywikibot/user-config.py ;
      fi ;
    fi
  - echo "authenticate['wiki.musicbrainz.org'] = ('NOTSPAM', 'NOTSPAM')" >> ~/.pywikibot/user-config.py ;

  - echo "max_retries = 2" >> ~/.pywikibot/user-config.py
  - echo "maximum_GET_length = 5000" >> ~/.pywikibot/user-config.py
  - echo "console_encoding = 'utf8'" >> ~/.pywikibot/user-config.py

  - python -c "import setuptools; print(setuptools.__version__)"

  - if [[ "$USE_NOSE" == "1" ]]; then
      nosetests --version ;
      if [[ "$SITE_ONLY" == "1" ]]; then
        python setup.py nosetests --tests tests --verbosity=2 -a "family=$FAMILY,code=$LANGUAGE" --with-trim --with-coverage --cover-package=. ;
      else
        python setup.py nosetests --tests tests --verbosity=2 --with-trim --with-coverage --cover-package=. ;
      fi ;
    elif [[ "$USE_PYTEST" == "1" ]]; then
      if [[ "$SITE_ONLY" == "1" ]]; then
        python setup.py pytest --addopts="-vvv -s --timeout=$TEST_TIMEOUT --cov=. -a \"family=='$FAMILY' and code=='$LANGUAGE'\"" ;
      else
        python setup.py pytest --addopts="-vvv -s --timeout=$TEST_TIMEOUT --cov=." ;
      fi
    else
      coverage run setup.py test ;
    fi

after_success:
    codecov

after_failure:
    codecov

env:
  global:
    # This is the encrypted password for Wikimedia SUL user 'Pywikibot-test',
    # and is only decrypted by Travis when running builds of code merged into
    # the github repository 'wikimedia/pywikibot-core'.
    # See http://docs.travis-ci.com/user/encryption-keys/ for more information.
    - secure: kofInMlisiTBt9o/Ustc/vySlkKfxGzGCX2LwA1D2waym8sDTS0o5gMJ5LsrT/BUKwZbe1vLozPHqZrrkQvsdTml+DpZuotzdILs0m0f3BUoexEC6OON5IDljuxFyETrD1Ug44ih5Mc4lVFOdTcBzg501ZmswGwQrBvg/OyEFfE=
    - TEST_TIMEOUT: 300

  matrix:
    - LANGUAGE=en FAMILY=wikipedia PYWIKIBOT2_TEST_PROD_ONLY=1
    - LANGUAGE=zh FAMILY=wikisource PYSETUP_TEST_EXTRAS=1 PYWIKIBOT2_TEST_PROD_ONLY=1 PYWIKIBOT2_TEST_NO_RC=1

# Note: 2.7_with_system_site_packages is equivalent to virtualenv: system_site_packages: true
matrix:
  include:
    # precise uses 2.7.3
    - python: '2.7_with_system_site_packages'
      env: LANGUAGE=he FAMILY=wikivoyage DIST=precise-sudo PYSETUP_TEST_EXTRAS=1 PYWIKIBOT2_TEST_NO_RC=1
      dist: precise
      sudo: required
      addons:
        apt:
          packages:
            - djvulibre-bin
              # 3.5.24-9ubuntu0.1
            - graphviz
              # 2.26.3-10ubuntu1.2
            - liblua5.1-0-dev
              # 5.1.4-12ubuntu1.1
            - python-bs4  # 4.0.2 ; diff broken: T136807
            - python-imaging  # 1.1.7-4ubuntu0.12.04.1
            - python-imaging-tk  # 1.1.7-4ubuntu0.12.04.1
            - python-ipaddr  # 2.1.10
            - python-lxml  # 2.3.2-1ubuntu0.2
            - python-pycountry  # 0.14.1+ds1-2
            - python-openssl  # preinstalled at latest version
            - python-stdnum  # 0.6-1
            - python-tz  # 2011k-0ubuntu5.1
            # dev requirements
            - python-coverage  # 3.4
            - python-six  # 1.1.0
            - python-unittest2  # 0.5.1
    # trusty uses 2.7.6
    - python: '2.7_with_system_site_packages'
      env: LANGUAGE=nb FAMILY=wikipedia DIST=trusty PYSETUP_TEST_EXTRAS=1
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - djvulibre-bin
              # 3.5.25.4-3
            - graphviz
              # 2.36.0-0ubuntu3.1
            - liblua5.1-0-dev
              # 5.1.5-5
            - python-bs4  # 4.2.1
            - python-imaging  # 2.3.0-1ubuntu3
            - python-ipaddr  # 2.1.10
            - python-lxml  # 3.3.3
            - python-openssl  # preinstalled at latest version
            - python-pil  # 2.3.0-1ubuntu3
            - python-pil.imagetk  # 2.3.0-1ubuntu3
            - python-pycountry  # 0.14.1+ds1-3build1
            - python-stdnum  # 0.9-2
            - python-tk  # 2.7.5
            - python-tz  # 2012c
            - python-unicodecsv  # 0.9.4
            # dev requirements
            - python-coverage  # 3.7.1+dfsg.1-1ubuntu2
            - python-mccabe  # 0.2.1
            - python-six  # pre-installed at latest version
            - python-unittest2  # 0.5.1
    - python: '2.7_with_system_site_packages'
      env: LANGUAGE=test FAMILY=wikipedia DIST=trusty+sid PYSETUP_TEST_EXTRAS=1
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - djvulibre-bin  # 3.5.27.1-5
            - graphviz  # 2.38.0-13
            - liblua5.1-0-dev  # 5.1.5-8
            # python-bs4  # 4.4.1
            # python-cryptography  # 1.3.1-2  causes errors due to SNI warnings
            # python-future  # 0.15.2-2
            # python-imaging  # 3.2.0-2
            - python-ipaddr  # 2.1.11
            # python-lxml  # 3.6.0
            # python-openssl  # 16.0.0  causes errors due to SNI warnings
            # python-pil  # 3.2.0-2
            # python-pil.imagetk
            - python-pycountry  # 1.8+ds1-0.1
            # python-requests  # 2.10.0  causes errors due to SNI warnings
            - python-stdnum  # 1.3
            # python-tk  # 2.7.11
            # python-tz  # 2015.7+dfsg-0.1
            - python-unicodecsv  # 0.14.1
            # dev requirements
            - pep8  # 1.7.0-2
            - pyflakes  # 1.2.3
            - python-coverage  # 3.7.1+dfsg.1-1+b2
            - python-pyflakes  # 1.2.3
            - python-six  # 1.10.0-3
            - python-unittest2  # 1.1.0-6.1
    - python: '2.7'
      env: LANGUAGE=en FAMILY=wpbeta SITE_ONLY=1 OAUTH_DOMAIN="en.wikipedia.beta.wmflabs.org"
    - python: '3.3'
      env: LANGUAGE=zh FAMILY=wpbeta SITE_ONLY=1 OAUTH_DOMAIN="zh.wikipedia.beta.wmflabs.org"
    - python: '3.4'
      env: LANGUAGE=en FAMILY=wsbeta SITE_ONLY=1
    - python: '2.7'
      env: LANGUAGE=wikia FAMILY=wikia PYWIKIBOT2_TEST_NO_RC=1
    - python: '3.3'
      env: LANGUAGE=en FAMILY=musicbrainz SITE_ONLY=1
    - python: '3.4'
      env: LANGUAGE=test FAMILY=wikipedia SITE_ONLY=1 OAUTH_DOMAIN="test.wikipedia.org"
    - python: '3.4'
      env: LANGUAGE=test FAMILY=wikidata SITE_ONLY=1
    - python: '3.4'
      env: LANGUAGE=ar FAMILY=wiktionary PYWIKIBOT2_TEST_NO_RC=1
    - python: '2.6'
      env: LANGUAGE=wikidata FAMILY=wikidata SITE_ONLY=1

notifications:
  email:
    recipients:
      - pywikibot-commits@lists.wikimedia.org
    on_success: always
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#pywikibot"
    on_success: change
    on_failure: change
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
