# See tests/README.rst for instructions for using travis with developer builds.

language: python

sudo: false

python:
  - '2.7'
  - '3.4'
  - 'pypy'

install:
  - pip install tox-travis

script:
  - tox

notifications:
  email:
    recipients:
      - pywikibot-commits@lists.wikimedia.org
    on_success: always
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#pywikibot"
    on_success: change
    on_failure: change
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
