language: python

python:
  - '2.7'
  - '3.3'
  - '2.6'

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y liblua5.1-dev

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install ordereddict unittest2==0.6.0; fi
  - pip install six
  - export GITHUB_USER=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 1`
  - mkdir ~/.pywikibot
  - mkdir ~/.python-eggs
  - chmod 700 ~/.python-eggs

  - touch ~/.pywikibot/user-config.py
  - echo "import os" >> ~/.pywikibot/user-config.py
  - echo "mylang = '$LANGUAGE'" >> ~/.pywikibot/user-config.py
  - echo "family = '$FAMILY'" >> ~/.pywikibot/user-config.py

  - echo "password_file = os.path.expanduser('~/.pywikibot/passwordfile')" >> ~/.pywikibot/user-config.py
  - touch ~/.pywikibot/passwordfile

  - echo "max_retries = 2" >> ~/.pywikibot/user-config.py
  - echo "maximum_GET_length = 5000" >> ~/.pywikibot/user-config.py
  - echo "http_threads = 5" >> ~/.pywikibot/user-config.py

  - if [[ "$GITHUB_USER" == "wikimedia" ]]; then PYWIKIBOT2_USERNAME="Pywikibot-test"; fi

  - if [[ -n "$USER_PASSWORD" && -n "$PYWIKIBOT2_USERNAME" ]]; then echo "usernames['$FAMILY']['$LANGUAGE'] = '$PYWIKIBOT2_USERNAME'" >> ~/.pywikibot/user-config.py; fi
  - if [[ -n "$USER_PASSWORD" && -n "$PYWIKIBOT2_USERNAME" ]]; then echo "usernames['wikipedia']['en'] = '$PYWIKIBOT2_USERNAME'" >> ~/.pywikibot/user-config.py; fi
  - if [[ -n "$USER_PASSWORD" && -n "$PYWIKIBOT2_USERNAME" ]]; then echo "usernames['wikipedia']['test'] = '$PYWIKIBOT2_USERNAME'" >> ~/.pywikibot/user-config.py; fi
  - if [[ -n "$USER_PASSWORD" && -n "$PYWIKIBOT2_USERNAME" ]]; then echo "usernames['wikidata']['test'] = '$PYWIKIBOT2_USERNAME'" >> ~/.pywikibot/user-config.py; fi

  - if [[ -n "$USER_PASSWORD" && -n "$PYWIKIBOT2_USERNAME" ]]; then echo "('$PYWIKIBOT2_USERNAME', '$USER_PASSWORD')" > ~/.pywikibot/passwordfile; fi

  - cd externals/httplib2
  - python setup.py install
  - cd ../..

  - python -c "import setuptools; print(setuptools.__version__)"

script:
  - if [[ "$USE_NOSE" == "1" ]]; then nosetests -v ; else python setup.py test; fi

env:
  global:
    # This is the encrypted password, which can only be decrypted by Travis itself
    # See http://docs.travis-ci.com/user/encryption-keys/
    # And http://docs.travis-ci.com/user/build-configuration/#Secure-environment-variables
    # Command use to generate: travis encrypt USER_PASSWORD=<pwd> -r wikimedia/pywikibot-core
    - secure: kofInMlisiTBt9o/Ustc/vySlkKfxGzGCX2LwA1D2waym8sDTS0o5gMJ5LsrT/BUKwZbe1vLozPHqZrrkQvsdTml+DpZuotzdILs0m0f3BUoexEC6OON5IDljuxFyETrD1Ug44ih5Mc4lVFOdTcBzg501ZmswGwQrBvg/OyEFfE=
  matrix:
    - LANGUAGE=en FAMILY=wikipedia
    - LANGUAGE=ar FAMILY=wikipedia PYSETUP_TEST_EXTRAS=1
    - LANGUAGE=test FAMILY=wikidata
    - LANGUAGE=fr FAMILY=wiktionary

notifications:
  email:
    recipients:
      - pywikibot-commits@lists.wikimedia.org
    on_success: always
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#pywikibot"
    on_success: change
    on_failure: change
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
