# See tests/README.rst for instructions for using travis with developer builds.

language: python

python:
  - '2.7_with_system_site_packages'
  - '3.3'
  - '2.6'

before_install:
  - export TRAVIS_PYTHON_VERSION_MAJOR="${TRAVIS_PYTHON_VERSION:0:1}"
  - if [[ "$TRAVIS_PYTHON_VERSION_MAJOR" == '3' ]]; then
      export export APT_PYTHON_PREFIX=python3 ;
    else
      export export APT_PYTHON_PREFIX=python ;
    fi
  - sudo apt-get update -qq
  - sudo apt-get install -y liblua5.1-dev
  - if [[ "$TRAVIS_PYTHON_VERSION" == '2.7_with_system_site_packages' ]]; then
      sudo pip install --upgrade httplib2 six ;
      if [[ "$USE_APT" == '1' ]]; then
        sudo apt-get install -y ${APT_PYTHON_PREFIX}-pygments ;
        sudo apt-get install -y python-irclib python-pycountry python-babel ;
      fi ;
    fi ;
  - if [[ "$TRAVIS_PYTHON_VERSION_MAJOR" == '3' ]]; then
      pip install six ;
    fi

install:
  - if [[ "$SITE_ONLY" == '1' ]]; then export USE_NOSE=1; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2==0.6.0; fi
  - export GITHUB_USER=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 1`
  - mkdir ~/.pywikibot
  - mkdir ~/.python-eggs
  - chmod 700 ~/.python-eggs

  - touch ~/.pywikibot/user-config.py
  - echo "import os" >> ~/.pywikibot/user-config.py
  - echo "mylang = '$LANGUAGE'" >> ~/.pywikibot/user-config.py
  - echo "family = '$FAMILY'" >> ~/.pywikibot/user-config.py

  - echo "password_file = os.path.expanduser('~/.pywikibot/passwordfile')" >> ~/.pywikibot/user-config.py
  - touch ~/.pywikibot/passwordfile

  - echo "max_retries = 2" >> ~/.pywikibot/user-config.py
  - echo "maximum_GET_length = 5000" >> ~/.pywikibot/user-config.py
  - echo "console_encoding = 'utf8'" >> ~/.pywikibot/user-config.py

  - if [[ "$GITHUB_USER" == "wikimedia" ]]; then
      PYWIKIBOT2_USERNAME="Pywikibot-test" ;
    else
      export PYWIKIBOT2_TEST_WRITE_FAIL=1 ;
    fi

  - if [[ -n "$USER_PASSWORD" && -n "$PYWIKIBOT2_USERNAME" ]]; then
      echo "usernames['$FAMILY']['$LANGUAGE'] = '$PYWIKIBOT2_USERNAME'" >> ~/.pywikibot/user-config.py ;
      echo "usernames['wikipedia']['en'] = '$PYWIKIBOT2_USERNAME'" >> ~/.pywikibot/user-config.py ;
      echo "usernames['wikipedia']['test'] = '$PYWIKIBOT2_USERNAME'" >> ~/.pywikibot/user-config.py ;
      echo "usernames['wikidata']['test'] = '$PYWIKIBOT2_USERNAME'" >> ~/.pywikibot/user-config.py ;
      echo "usernames['commons']['commons'] = '$PYWIKIBOT2_USERNAME'" >> ~/.pywikibot/user-config.py ;
      echo "('$PYWIKIBOT2_USERNAME', '$USER_PASSWORD')" > ~/.pywikibot/passwordfile ;
    fi

  - rm -rf externals/httplib2

  - python -c "import setuptools; print(setuptools.__version__)"

script:
  - if [[ "$USE_NOSE" == "1" ]]; then
      if [[ "$SITE_ONLY" == "1" ]]; then
        echo "Running site tests only code ${LANGUAGE} on family ${FAMILY}" ;
        python setup.py nosetests --tests tests -v -a "family=$FAMILY,code=$LANGUAGE" ;
      else
        python setup.py nosetests --tests tests -v ;
      fi ;
    else
      python setup.py test ;
    fi

env:
  global:
    # This is the encrypted password for Wikimedia SUL user 'Pywikibot-test',
    # and is only decrypted by Travis when running builds of code merged into
    # the github repository 'wikimedia/pywikibot-core'.
    # See http://docs.travis-ci.com/user/encryption-keys/ for more information.
    - secure: kofInMlisiTBt9o/Ustc/vySlkKfxGzGCX2LwA1D2waym8sDTS0o5gMJ5LsrT/BUKwZbe1vLozPHqZrrkQvsdTml+DpZuotzdILs0m0f3BUoexEC6OON5IDljuxFyETrD1Ug44ih5Mc4lVFOdTcBzg501ZmswGwQrBvg/OyEFfE=
  matrix:
    - LANGUAGE=en FAMILY=wikipedia
    - LANGUAGE=ar FAMILY=wikipedia PYSETUP_TEST_EXTRAS=1 USE_APT=1
    - LANGUAGE=test FAMILY=wikidata SITE_ONLY=1
    - LANGUAGE=fr FAMILY=wiktionary SITE_ONLY=1 USE_APT=1

notifications:
  email:
    recipients:
      - pywikibot-commits@lists.wikimedia.org
    on_success: always
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#pywikibot"
    on_success: change
    on_failure: change
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
